name: Check PR

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  validate:
    name: lint (pr)
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            deprecate
            remove
            security
            perf
            docs
            refactor
            test
            build
            ci
            chore
            revert

          requireScope: false

          subjectPattern: ^[A-Z].+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            should start with an uppercase letter.

            Good:
              fix: Prevent a stuck config value
              feat: Add long range constraints

            Bad:
              fix: prevent a stuck config value
